const PERIOD_LABELS={"1M":"1 個月","3M":"3 個月","YTD":"今年以來","1Y":"1 年","3Y":"3 年","SI":"共同期間"};
const SERIES_LABELS={NDXTR_USD:"NDXTR 美元",NDXTR_TWD:"NDXTR 新台幣",QQQ:"QQQ",00662:"00662",009800:"009800"};
const CHART_COLORS={NDXTR_USD:"#202b45",NDXTR_TWD:"#8893aa",QQQ:"#596cff",00662:"#15a57a",009800:"#d58b19"};
let payload=null;let selected="1Y";
const fmt=(n,d=2)=>Number.isFinite(n)?`${n.toFixed(d)}%`:"—";
async function load(){try{const r=await fetch(`data/tracking.json?v=${Date.now()}`,{cache:"no-store"});if(!r.ok)throw new Error(`HTTP ${r.status}`);payload=await r.json();renderShell();}catch(e){document.querySelector("#sourceNote").textContent=`讀取資料失敗：${e.message}`;}}
function renderShell(){const status=document.querySelector("#statusBadge");status.className=`status ${payload.status||"waiting"}`;status.textContent=payload.status==="ok"?"資料已更新":payload.status==="partial"?"部分資料可用":"等待首次更新";document.querySelector("#asOf").textContent=payload.asOf||"—";document.querySelector("#sourceNote").textContent=`${payload.source?.note||"尚未取得資料。"} 本站為研究工具，不構成投資建議。`;renderButtons();renderPeriod();drawChart();}
function renderButtons(){const box=document.querySelector("#periodButtons");box.innerHTML="";Object.entries(PERIOD_LABELS).forEach(([code,label])=>{const b=document.createElement("button");b.textContent=label;b.className=code===selected?"active":"";b.onclick=()=>{selected=code;renderButtons();renderPeriod();};box.appendChild(b);});}
function renderPeriod(){const rows=payload.periods?.[selected]?.rows||[];const winner=rows[0];document.querySelector("#winnerSymbol").textContent=winner?.symbol||"—";document.querySelector("#winnerScore").textContent=winner?`${winner.score}/100`:"—";document.querySelector("#winnerReason").textContent=winner?`追蹤差距 ${fmt(winner.difference)}，年化追蹤誤差 ${fmt(winner.trackingError)}`:"等待 GitHub Actions 取得每日資料";const cards=document.querySelector("#summaryCards");cards.innerHTML=["QQQ","00662","009800"].map(symbol=>{const row=rows.find(r=>r.symbol===symbol);return `<article class="metric-card"><small>${symbol}</small><strong>${row?row.score:"—"}</strong><p>${row?`差距 ${fmt(row.difference)} · 誤差 ${fmt(row.trackingError)}`:"等待資料"}</p></article>`;}).join("")+`<article class="metric-card"><small>有效交易日</small><strong>${winner?.days||"—"}</strong><p>${PERIOD_LABELS[selected]}共同可比較樣本</p></article>`;const body=document.querySelector("#comparisonBody");if(!rows.length){body.innerHTML='<tr><td colspan="7" class="empty">尚無可比較資料，請先執行 GitHub Actions。</td></tr>';return;}body.innerHTML=rows.map(r=>`<tr><td>${r.symbol}<br><small>${SERIES_LABELS[r.benchmark]}</small></td><td>${fmt(r.return)}</td><td>${fmt(r.benchmarkReturn)}</td><td class="${r.difference>=0?"positive":"negative"}">${fmt(r.difference)}</td><td>${fmt(r.trackingError)}</td><td><span class="score-pill">${r.score}</span></td><td>${r.days}</td></tr>`).join("");}
function drawChart(){const canvas=document.querySelector("#performanceChart"),ctx=canvas.getContext("2d"),ratio=window.devicePixelRatio||1;const cssWidth=canvas.clientWidth||1200,cssHeight=Math.max(280,cssWidth*.36);canvas.width=cssWidth*ratio;canvas.height=cssHeight*ratio;ctx.scale(ratio,ratio);ctx.clearRect(0,0,cssWidth,cssHeight);const all=payload.chart||{};const entries=Object.entries(all).filter(([,a])=>a?.length>1);const legend=document.querySelector("#legend");legend.innerHTML=entries.map(([s])=>`<span><i style="background:${CHART_COLORS[s]}"></i>${SERIES_LABELS[s]}</span>`).join("");if(!entries.length){ctx.fillStyle="#7a859b";ctx.font="16px sans-serif";ctx.textAlign="center";ctx.fillText("等待首次 GitHub Actions 更新",cssWidth/2,cssHeight/2);return;}const values=entries.flatMap(([,a])=>a.map(p=>p.value));const min=Math.min(...values),max=Math.max(...values),pad=42;ctx.strokeStyle="#e6eaf2";ctx.lineWidth=1;for(let i=0;i<5;i++){const y=pad+(cssHeight-pad*2)*i/4;ctx.beginPath();ctx.moveTo(pad,y);ctx.lineTo(cssWidth-pad,y);ctx.stroke();}entries.forEach(([symbol,points])=>{ctx.strokeStyle=CHART_COLORS[symbol];ctx.lineWidth=symbol.startsWith("NDXTR")?1.6:2.6;ctx.beginPath();points.forEach((p,i)=>{const x=pad+(cssWidth-pad*2)*i/(points.length-1);const y=cssHeight-pad-(p.value-min)/(max-min||1)*(cssHeight-pad*2);i?ctx.lineTo(x,y):ctx.moveTo(x,y);});ctx.stroke();});}
window.addEventListener("resize",()=>payload&&drawChart());load();
